version: "3"
services:
  optimus_media_api:
    container_name: oms
    build:
      context: "./"
    environment:
      - DOPPLER_TOKEN=${DOPPLER_TOKEN}
    command:
      [
        "doppler",
        "run",
        "--",
        "pdm",
        "run",
        "uvicorn",
        "optimus_portfolio_api.app:app",
        "--host",
        "0.0.0.0",
      ]
    volumes:
      - /${MEDIA_PATH}:/stored_media/images
    networks:
      - webservice-network

networks:
  webservice-network:
    external:
      name: webservice-network
